title: Nick's Bag of Tricks
author: Nick Ulle
copyright: "2022"
exclude_patterns: [_build, .pixi]
only_build_toc_files: true

repository:
  url: https://github.com/nick-ulle/workflow-datasci

parse:
  myst_enable_extensions:
    # - amsmath
    - colon_fence
    # - deflist
    - dollarmath
    # - html_admonition
    - html_image
    - linkify
    # - replacements
    # - smartquotes
    - substitution

execute:
  execute_notebooks: auto

html:
  favicon: img/card-file-box.png
  use_repository_button: true
